POST http://localhost:5004/auth/register
Content-Type: application/json

{
  "email": "m@example.com",
  "password": "password123"
}

###login
POST http://localhost:5004/auth/login
Content-Type: application/json

{
  "email": "m@example.com",
  "password": "password123"
}